spring.datasource.url=jdbc:mysql://localhost:3306/audit_log?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createTableIfNotExist=true
spring.datasource.username=root
spring.datasource.password=2479308